# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            pfeiffer.ai
tagline:          'Jonas Pfeiffer'
description:      'Im a first year PhD student at the <a href="https://www.informatik.tu-darmstadt.de/ukp/ukp_home/index.en.jsp" target="_blank">UKP Lab at TU Darmstadt</a>. I work on NLP problems basically all the time because I dont have any private life outside the field... '
url:              http://www.pfeiffer.ai
baseurl:          /

author:
  name:           'Jonas Pfeiffer'
  url:            https://twitter.com/PfeiffJo

# paginate:         5

# # Custom vars
# version:          2.1.0

# github:
#   repo:           https://github.com/poole/hyde
